### PR TITLE
fix: invalid ssh key file

### PR DESCRIPTION
**Pull request by capric98**
Problem:
gofs will always throw an error of "invalid ssh key file" when using ssh_key authentication, the problem is from: https://github.com/no-src/gofs/blob/e14bbcb6290010524f68bcd99dc7e74907bb1351/driver/sftp/sftp.go#L109-L120
where `keyFileName` is not `"known_hosts"`.

Refer to the example from golang.org/x/crypto/ssh, we could use `ssh.InsecureIgnoreHostKey()` as HostKeyCallback function temporarily, because seems like `ssh.ParseKnownHosts(keyData)` has some other issue, and the host may not be in `known_hosts` file already.

Instead, the private key file could be parsed by `ssh.ParsePrivateKey()` to be a `ssh.Signer` and then `ssh.PublicKeys()` will convert it to `ssh.AuthMethod`.

### CODE REVIEW

**Comment by mstmdev** [comment]
I remove the `-ssh_key` flag and add some parameters to `-source` and `-dest` flags: `ssh_user`, `ssh_pass`, `ssh_key`, `ssh_key_pass`, `ssh_host_key`.

Use the above parameters to control the sftp authentication, for example:
`sftp://127.0.0.1:22?mode=server&local_sync_disabled=true&path=./source&remote_path=/home/remote/dest&ssh_user=sftp_user&ssh_pass=sftp_pwd&ssh_key=./id_rsa&ssh_key_pass=123456&ssh_host_key=/root/.ssh/known_hosts`

**Review by capric98 — COMMENTED** [review]
Passing ssh parameters via src/dest string looks more elegant than before, appreciate that!
Just one thing:
If `HostKey` is empty, before using `ssh.InsecureIgnoreHostKey()` maybe we could throw a warning log let the user know it could be set to enhance the security? Since we do have the option now.

**Comment by mstmdev** [comment]
Great idea, a warning log will be printed when the host key is empty.
Please review it again. @capric98

**Review by capric98 — COMMENTED** [review]
looks good to me, thanks!

**Comment by mstmdev** [comment]
Merged.

**Pull request merged**
